from enum import Enum


class FeatureType(Enum):
    DISTANCE_BETWEEN_EYES = "DISTANCE_BETWEEN_EYES"
    CHIN_HEIGHT = 'CHIN_HEIGHT'
    FOREHEAD_HEIGHT = 'FOREHEAD_HEIGHT'
    NOSE_WIDTH = 'NOSE_WIDTH'
    NOSE_LENGTH = 'NOSE_LENGTH'
    DISTANCE_BETWEEN_EARS = 'DISTANCE_BETWEEN_EARS'
